[build-system]
requires = ["setuptools>=42.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 79
include = """
(
    ^/tests/
  | ^/src/hannah/
  | ^/setup[.]py
)
"""
exclude = """
(
    .git
    .mypy_cache
    .tox
    __pycache__
    build
    dist
)
"""
